### ISSUE TITLE
Authorize-ServiceEncryptionRollover.ps1 returns 'Unauthorized'.

### ISSUE THREAD

**Issue by FumiakiNagano** [anoobbacker/storsimpledevicemgmttools#2]
When I executed Authorize-ServiceEncryptionRollover.ps1, it returned 'Unauthorized'

> C:\scripts\StorSimpleSDKTools\Authorize-ServiceEncryptionRollover.ps1 : Exception calling
"AuthorizeForServiceEncryptionKeyRollover" with "4" argument(s): "Operation returned an invalid status code
'**Unauthorized**'"
At line:1 char:1
\+ .\Authorize-ServiceEncryptionRollover.ps1 -SubscriptionId 45ad10be-9c ...
\+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    \+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    \+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Authorize-ServiceEncryptionRollover.ps
   1

If I changed “$DomainId” (= line # 80) to my default directory’s tenant ID, the issue solved.
I believe “$DomainId” need to be changed to my default directory’s tenant ID. Is this correct?

**Comment by anoobbacker** [comment]
Thanks for reporting this. We're working on this to be fixed.

**Comment by bkrishna-hari** [comment]
@FumiakiNagano 
Fixed "Unauthorized" issue and updated the scripts.
Changed the TenantId variable to DomainId in the code. Added TenantId input into param list.

Can you please take latest scripts and use/verify it.  Please let me know, if you need any assistance.

Thank you.
