### ISSUE TITLE
Any chance in a sample without the popup authentication. 

### ISSUE THREAD

**Issue by daerhtthread** [anoobbacker/storsimpledevicemgmttools#7]
Any chance in a sample without the popup authentication. 
But using a service principal name so we can schedule it.

**Comment by anoobbacker** [comment]
Thanks for the suggestion, we'll get back on this. Meanwhile, refer [Authentication SDK doc](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/Authentication.md).

**Comment by anoobbacker** [comment]
We just submitted a script [here](https://github.com/anoobbacker/storsimpledevicemgmttools/blob/master/Get-DeviceJobs.ps1) which has the option to do silent authentication. Hope that addresses the issue. Hence marking this as closed.
